#!/bin/bash
# ---------------------------------------------------------------------------------------------
# Turns the white-label table into working nginx hosts.
#
# A global admin adds a customer domain in the dashboard; this script gives it a server block, and
# a certificate once its DNS points here. It runs every two minutes and does nothing at all when
# there is nothing to do, so the usual cost of it existing is one HTTP request.
#
# Two kinds of customer are supported without asking which is which: one points an A record at us
# (we obtain the certificate), another keeps their own reverse proxy in front and forwards to us
# (they hold the certificate; the port-80 block is what serves them). Both get the same block.
# ---------------------------------------------------------------------------------------------
set -uo pipefail

API="${PORTAL_API:-https://docurest.com/api/portal/hosts}"
TOKEN="${PORTAL_JOB_TOKEN:-}"
PUBLIC_IP="${PORTAL_PUBLIC_IP:-77.42.95.87}"
EMAIL="${PORTAL_CERT_EMAIL:-hcoder@gmail.com}"
ENABLED_DIR=/etc/nginx/sites-enabled
PREFIX=portal-
LOG=/var/log/portal-sync.log

log() { echo "$(date -Is) $*" >> "$LOG"; }

[ -z "$TOKEN" ] && { log "no PORTAL_JOB_TOKEN set — nothing to do"; exit 0; }

hosts=$(curl -sf --max-time 20 -H "Authorization: Bearer $TOKEN" "$API") || {
  log "could not read the host list from $API"; exit 0;
}

changed=0
wanted=""

for host in $hosts; do
  # Never let a name from a table become a shell argument unchecked.
  if ! [[ "$host" =~ ^[a-z0-9.-]+\.[a-z]{2,}$ ]]; then
    log "skipping a host that is not a plain host name: $host"
    continue
  fi
  conf="$ENABLED_DIR/${PREFIX}${host}.conf"
  live="/etc/letsencrypt/live/$host"

  # Never fight a hand-written block. A host that already has one (WIUT's, say) is served by it;
  # generating a second would make nginx pick one by filename order and warn about the other,
  # which is a confusing way to find out that an edit went to the file that is being ignored.
  if grep -RlE "^[[:space:]]*server_name[^;]*[[:space:].]$host[[:space:];]" "$ENABLED_DIR" 2>/dev/null        | grep -qv "${PREFIX}${host}.conf"; then
    [ -e "$conf" ] && { rm -f "$conf"; changed=1; log "removed $conf — $host has a hand-written block"; }
    log "skipping $host: served by a hand-written block"
    continue
  fi

  wanted="$wanted $host"

  # A certificate, but only when the name actually points at this machine: asking Let's Encrypt
  # for one that cannot be validated earns a rate limit, and the customer may be fronting us.
  if [ ! -d "$live" ] && dig +short "$host" | grep -qx "$PUBLIC_IP"; then
    log "obtaining a certificate for $host"
    certbot certonly --webroot -w /var/www/html -d "$host" \
        --non-interactive --agree-tos -m "$EMAIL" >> "$LOG" 2>&1 \
      && log "certificate obtained for $host" \
      || log "certbot failed for $host (see above)"
  fi

  # The block itself. Rendered fresh each time so a certificate appearing later upgrades it.
  tmp=$(mktemp)
  {
    echo "# Generated by portal-sync.sh from the white-label table. Do not edit by hand."
    echo "server {"
    echo "    listen 80;"
    echo "    server_name $host;"
    if [ -d "$live" ]; then
      # We hold the certificate, so plain HTTP is only for the ACME challenge.
      echo "    location /.well-known/acme-challenge/ { root /var/www/html; }"
      echo "    location / { return 301 https://\$host\$request_uri; }"
      echo "}"
      echo "server {"
      echo "    listen 443 ssl http2;"
      echo "    server_name $host;"
      echo "    ssl_certificate $live/fullchain.pem;"
      echo "    ssl_certificate_key $live/privkey.pem;"
      echo "    include /etc/letsencrypt/options-ssl-nginx.conf;"
      echo "    include /etc/nginx/snippets/portal-app.conf;"
      echo "}"
    else
      # No certificate here: the customer terminates TLS themselves and forwards to this block.
      echo "    include /etc/nginx/snippets/portal-app.conf;"
      echo "}"
    fi
  } > "$tmp"

  if ! cmp -s "$tmp" "$conf" 2>/dev/null; then
    mv "$tmp" "$conf"; changed=1; log "wrote $conf"
  else
    rm -f "$tmp"
  fi
done

# A host removed from the table stops being served.
for conf in "$ENABLED_DIR"/${PREFIX}*.conf; do
  [ -e "$conf" ] || continue
  host=$(basename "$conf" .conf); host=${host#$PREFIX}
  case " $wanted " in
    *" $host "*) ;;
    *) rm -f "$conf"; changed=1; log "removed $conf (no longer in the table)" ;;
  esac
done

if [ "$changed" = "1" ]; then
  if nginx -t >> "$LOG" 2>&1; then
    systemctl reload nginx && log "nginx reloaded"
  else
    log "NGINX CONFIG INVALID — not reloading; see above"
  fi
fi
